# Generated by Django 2.0.6 on 2018-06-29 16:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('text_msg', '0002_auto_20180629_1301'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='fist_name',
            new_name='first_name',
        ),
    ]
